version: '3'
services:
  Client:
    build: .
    image: filesharing_client:0.2.1
    ports:
      - "8081:8081"
    volumes:
      - ../Client:/Client:rw
      - ./client.sh:/client.sh:ro
    environment:
      - user_id=$user_id
      - user=$user
    command: /bin/sh -c "/client.sh"
  Server:
    build: .
    image: filesharing_server:0.2.1
    ports:
      - "8082:8082"
    volumes:
      - ../Server:/Server:rw
      - ./server.sh:/server.sh:ro
    environment:
      - user_id=$user_id
      - user=$user
    command: /bin/sh -c "/server.sh"
